[package]
name = "client"
version = "0.1.0"
edition = "2021"

# NOTE: Workspace dependencies are referenced with the local path
[dependencies.core_compat]
path = "../core_compat"

[dependencies.geometry]
path = "../geometry"

[dependencies]
bevy = { version = "0.19.1", features = ["bevy_asset"]}
bevy_framepace = "0.22.0"
thiserror = "2.0.18"
ron = "*"
bevy_egui = "0.42.0"
