[package]
name = "data_converter"
version = "0.1.0"
authors = ["cjschneider2 <cjschneider2@gmail.com>"]

[dependencies.core_compat]
path = "../core_compat"

[dependencies]
png = "0.17.2"
xml_writer = "*"
