[package]
name = "core_compat"
version = "0.0.1"
authors = ["C. Jeremiah Schneider <cjschneider2@gmail.com>"]

[dependencies.geometry]
path = "../geometry"

[dependencies.cp949]
path = "../cp949"

[dependencies]
byteorder = "*"

[dev-dependencies]
png = "0.17.2"
